//! # flux-importer
//!
//! Translates [Flux bytecode](flux_core) into synthetic MIR that can be consumed
//! by the cuda-oxide compilation pipeline (`mir-importer` → `mir-lower` → `llvm-export` → PTX).
//!
//! ## Architecture Position
//!
//! ```text
//! Agent Intent
//!     ↓ (LLM / user / agent)
//! Flux Bytecode
//!     ↓ THIS CRATE (flux-importer)
//! Synthetic MIR (compatible with cuda-oxide mir-importer output)
//!     ↓ mir-lower
//! Pliron IR (NVVM dialect)
//!     ↓ llvm-export
//! LLVM IR → PTX
//! ```
//!
//! ## Why Flux?
//!
//! Flux bytecode is agent-native — it can be generated by LLMs, compiled from
//! higher-level DSLs, or hand-written. By inserting a Flux→MIR bridge before the
//! cuda-oxide pipeline, we enable *agents to compile their own GPU work* without
//! needing to generate Rust source code.
//!
//! ## Quick Start
//!
//! ```rust,ignore
//! use flux_importer::{FluxToMir, ImportConfig};
//! use flux_core::bytecode::opcodes::Op;
//!
//! let bytecode = vec![Op::MOVI as u8, 0, 42, 0, Op::HALT as u8];
//! let config = ImportConfig::default();
//! let mir = FluxToMir::translate(&bytecode, &config)?;
//! // `mir` is now synthetic MIR compatible with cuda-oxide's pipeline
//! ```

use std::collections::HashMap;

/// Errors that can occur during Flux→MIR translation.
#[derive(Debug, Clone)]
pub enum ImportError {
    /// Invalid opcode at the given offset.
    InvalidOpcode { offset: usize, byte: u8 },
    /// Bytecode ended unexpectedly.
    UnexpectedEnd { offset: usize, expected: usize },
    /// Register index out of bounds.
    RegisterOutOfBounds { index: usize, max: usize },
    /// Jump target is invalid.
    InvalidJump { from: usize, to: usize },
    /// Unsupported operation for GPU compilation.
    UnsupportedGpu { op: String, reason: String },
}

impl std::fmt::Display for ImportError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ImportError::InvalidOpcode { offset, byte } => {
                write!(f, "invalid opcode 0x{byte:02x} at offset {offset}")
            }
            ImportError::UnexpectedEnd { offset, expected } => {
                write!(f, "bytecode ended at offset {offset}, expected {expected} more bytes")
            }
            ImportError::RegisterOutOfBounds { index, max } => {
                write!(f, "register {index} out of bounds (max {max})")
            }
            ImportError::InvalidJump { from, to } => {
                write!(f, "invalid jump from {from} to {to}")
            }
            ImportError::UnsupportedGpu { op, reason } => {
                write!(f, "unsupported GPU operation '{op}': {reason}")
            }
        }
    }
}

impl std::error::Error for ImportError {}

/// Configuration for the Flux→MIR translation.
#[derive(Debug, Clone)]
pub struct ImportConfig {
    /// Maximum number of general-purpose registers.
    pub max_gp_registers: usize,
    /// Maximum number of floating-point registers.
    pub max_fp_registers: usize,
    /// Whether to enable GPU-specific optimizations.
    pub gpu_optimizations: bool,
    /// Target CUDA compute capability (e.g., 80 for SM_80).
    pub compute_capability: u32,
    /// Maximum number of threads per block.
    pub max_threads_per_block: u32,
}

impl Default for ImportConfig {
    fn default() -> Self {
        Self {
            max_gp_registers: 256,
            max_fp_registers: 256,
            gpu_optimizations: true,
            compute_capability: 80,
            max_threads_per_block: 1024,
        }
    }
}

/// A synthetic MIR basic block, compatible with cuda-oxide's pipeline.
#[derive(Debug, Clone)]
pub struct MirBlock {
    /// Block label (for jumps).
    pub label: String,
    /// Ordered list of statements.
    pub statements: Vec<MirStatement>,
    /// Terminator (jump, branch, return, etc.).
    pub terminator: MirTerminator,
}

/// A statement in synthetic MIR.
#[derive(Debug, Clone)]
pub enum MirStatement {
    /// Assign a value to a place.
    Assign {
        destination: String,
        value: MirValue,
    },
    /// Load from memory.
    Load {
        destination: String,
        source: String,
        ty: MirType,
    },
    /// Store to memory.
    Store {
        destination: String,
        value: String,
        ty: MirType,
    },
    /// GPU-specific: shared memory barrier.
    SyncThreads,
    /// GPU-specific: get thread index.
    ThreadIndex {
        dim: u32,  // 0=x, 1=y, 2=z
        destination: String,
    },
    /// GPU-specific: get block dimension.
    BlockDim {
        dim: u32,
        destination: String,
    },
}

/// A value in synthetic MIR.
#[derive(Debug, Clone)]
pub enum MirValue {
    /// Constant integer.
    ConstInt(i64),
    /// Constant float.
    ConstFloat(f64),
    /// Constant bool.
    ConstBool(bool),
    /// Read a register/place.
    Use(String),
    /// Binary operation.
    BinaryOp {
        op: MirBinOp,
        left: Box<MirValue>,
        right: Box<MirValue>,
    },
    /// Unary operation.
    UnaryOp {
        op: MirUnOp,
        operand: Box<MirValue>,
    },
    /// Ternary operation (native {-1, 0, +1}).
    TernaryOp {
        op: MirTernaryOp,
        a: Box<MirValue>,
        b: Box<MirValue>,
    },
    /// Intrinsic function call.
    Intrinsic {
        name: String,
        args: Vec<MirValue>,
    },
}

/// Binary operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MirBinOp {
    Add, Sub, Mul, Div, Rem,
    BitAnd, BitOr, BitXor, Shl, Shr,
    Eq, Ne, Lt, Le, Gt, Ge,
    And, Or,
}

/// Unary operations.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MirUnOp {
    Neg, Not, Abs,
}

/// Ternary operations (first-class {-1, 0, +1}).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MirTernaryOp {
    /// Ternary addition: {-1,0,+1} + {-1,0,+1} → {-1,0,+1}
    TAdd,
    /// Ternary multiplication: {-1,0,+1} × {-1,0,+1} → {-1,0,+1}
    TMul,
    /// Ternary compose (cascade).
    TCompose,
    /// Ternary consensus (vote).
    TConsensus,
}

/// MIR types.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum MirType {
    I8, I16, I32, I64,
    F32, F64,
    Bool,
    /// Ternary value {-1, 0, +1}.
    Ternary,
    /// GPU pointer with address space.
    GpuPointer {
        pointee: Box<MirType>,
        address_space: GpuAddressSpace,
    },
}

/// GPU address spaces.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum GpuAddressSpace {
    /// Global device memory.
    Global,
    /// Shared block memory.
    Shared,
    /// Constant memory.
    Constant,
    /// Local (per-thread) memory.
    Local,
}

/// Block terminators.
#[derive(Debug, Clone)]
pub enum MirTerminator {
    /// Unconditional jump.
    Goto(String),
    /// Conditional branch.
    Branch {
        condition: String,
        true_block: String,
        false_block: String,
    },
    /// Return from function.
    Return,
    /// Unreachable.
    Unreachable,
    /// GPU kernel return (writes to output buffer).
    KernelReturn { value: String },
}

/// A complete synthetic MIR function.
#[derive(Debug, Clone)]
pub struct MirFunction {
    /// Function name.
    pub name: String,
    /// Parameters.
    pub params: Vec<(String, MirType)>,
    /// Return type.
    pub return_type: Option<MirType>,
    /// Basic blocks.
    pub blocks: Vec<MirBlock>,
    /// GPU kernel metadata.
    pub gpu_meta: Option<GpuKernelMeta>,
}

/// GPU kernel metadata.
#[derive(Debug, Clone)]
pub struct GpuKernelMeta {
    /// Grid dimensions (x, y, z).
    pub grid_dim: (u32, u32, u32),
    /// Block dimensions (x, y, z).
    pub block_dim: (u32, u32, u32),
    /// Shared memory size in bytes.
    pub shared_mem_bytes: u32,
    /// Whether this kernel uses tensor cores.
    pub uses_tensor_cores: bool,
}

/// A complete synthetic MIR module (collection of functions).
#[derive(Debug, Clone)]
pub struct MirModule {
    /// Module name.
    pub name: String,
    /// Functions in this module.
    pub functions: Vec<MirFunction>,
    /// Imported constructs (git-native dependencies).
    pub imports: Vec<ConstructImport>,
}

/// A construct import — references a git-native GPU capability.
#[derive(Debug, Clone)]
pub struct ConstructImport {
    /// Git repository URL.
    pub repo: String,
    /// Version (git tag or commit hash).
    pub version: String,
    /// The specific kernel/function being imported.
    pub symbol: String,
    /// The construct's DID (identity verification).
    pub identity_did: Option<String>,
}

/// The main translator: Flux bytecode → synthetic MIR.
pub struct FluxToMir {
    config: ImportConfig,
    /// General-purpose registers.
    gp_registers: HashMap<u8, String>,
    /// Floating-point registers.
    fp_registers: HashMap<u8, String>,
    /// Named variables (from register mapping).
    variables: HashMap<String, MirValue>,
    /// Current block being built.
    current_block: Vec<MirStatement>,
    /// All completed blocks.
    blocks: Vec<MirBlock>,
    /// Block counter for generating labels.
    block_counter: usize,
}

impl FluxToMir {
    /// Create a new translator with the given configuration.
    pub fn new(config: ImportConfig) -> Self {
        Self {
            config,
            gp_registers: HashMap::new(),
            fp_registers: HashMap::new(),
            variables: HashMap::new(),
            current_block: Vec::new(),
            blocks: Vec::new(),
            block_counter: 0,
        }
    }

    /// Translate Flux bytecode to synthetic MIR.
    pub fn translate(bytecode: &[u8], config: &ImportConfig) -> Result<MirModule, ImportError> {
        let mut translator = Self::new(config.clone());
        translator.translate_module(bytecode)
    }

    fn translate_module(&mut self, bytecode: &[u8]) -> Result<MirModule, ImportError> {
        let mut pc = 0;
        let mut functions = Vec::new();

        while pc < bytecode.len() {
            let op = bytecode[pc];
            match op {
                0x00 => {
                    // HALT — end of module
                    break;
                }
                _ => {
                    // Process instruction
                    let consumed = self.translate_instruction(bytecode, pc)?;
                    pc += consumed;
                }
            }
        }

        // Flush remaining block
        self.flush_block(MirTerminator::Return);

        let func = MirFunction {
            name: "flux_main".to_string(),
            params: Vec::new(),
            return_type: None,
            blocks: self.blocks.clone(),
            gpu_meta: Some(GpuKernelMeta {
                grid_dim: (1, 1, 1),
                block_dim: (self.config.max_threads_per_block, 1, 1),
                shared_mem_bytes: 0,
                uses_tensor_cores: false,
            }),
        };
        functions.push(func);

        Ok(MirModule {
            name: "flux_module".to_string(),
            functions,
            imports: Vec::new(),
        })
    }

    fn translate_instruction(&mut self, bytecode: &[u8], pc: usize) -> Result<usize, ImportError> {
        if pc >= bytecode.len() {
            return Err(ImportError::UnexpectedEnd { offset: pc, expected: 1 });
        }

        let op = bytecode[pc];
        match op {
            0x01 => {
                // MOVI Rd, imm16 — move immediate to register
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let reg = bytecode[pc + 1] as usize;
                let imm = u16::from_le_bytes([bytecode[pc + 2], bytecode[pc + 3]]) as i64;
                let dest = format!("gp_{}", reg);
                self.gp_registers.insert(reg as u8, dest.clone());
                self.current_block.push(MirStatement::Assign {
                    destination: dest,
                    value: MirValue::ConstInt(imm),
                });
                Ok(4)
            }
            0x02 => {
                // ADD Rd, Rs1, Rs2 — integer addition
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let rs1 = format!("gp_{}", bytecode[pc + 2] as usize);
                let rs2 = format!("gp_{}", bytecode[pc + 3] as usize);
                self.current_block.push(MirStatement::Assign {
                    destination: rd,
                    value: MirValue::BinaryOp {
                        op: MirBinOp::Add,
                        left: Box::new(MirValue::Use(rs1)),
                        right: Box::new(MirValue::Use(rs2)),
                    },
                });
                Ok(4)
            }
            0x03 => {
                // SUB Rd, Rs1, Rs2
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let rs1 = format!("gp_{}", bytecode[pc + 2] as usize);
                let rs2 = format!("gp_{}", bytecode[pc + 3] as usize);
                self.current_block.push(MirStatement::Assign {
                    destination: rd,
                    value: MirValue::BinaryOp {
                        op: MirBinOp::Sub,
                        left: Box::new(MirValue::Use(rs1)),
                        right: Box::new(MirValue::Use(rs2)),
                    },
                });
                Ok(4)
            }
            0x04 => {
                // MUL Rd, Rs1, Rs2
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let rs1 = format!("gp_{}", bytecode[pc + 2] as usize);
                let rs2 = format!("gp_{}", bytecode[pc + 3] as usize);
                self.current_block.push(MirStatement::Assign {
                    destination: rd,
                    value: MirValue::BinaryOp {
                        op: MirBinOp::Mul,
                        left: Box::new(MirValue::Use(rs1)),
                        right: Box::new(MirValue::Use(rs2)),
                    },
                });
                Ok(4)
            }
            0x10 => {
                // TADD Rd, Ra, Rb — ternary addition (first-class)
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let ra = format!("gp_{}", bytecode[pc + 2] as usize);
                let rb = format!("gp_{}", bytecode[pc + 3] as usize);
                self.current_block.push(MirStatement::Assign {
                    destination: rd,
                    value: MirValue::TernaryOp {
                        op: MirTernaryOp::TAdd,
                        a: Box::new(MirValue::Use(ra)),
                        b: Box::new(MirValue::Use(rb)),
                    },
                });
                Ok(4)
            }
            0x11 => {
                // TMUL Rd, Ra, Rb — ternary multiplication
                if pc + 3 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 3 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let ra = format!("gp_{}", bytecode[pc + 2] as usize);
                let rb = format!("gp_{}", bytecode[pc + 3] as usize);
                self.current_block.push(MirStatement::Assign {
                    destination: rd,
                    value: MirValue::TernaryOp {
                        op: MirTernaryOp::TMul,
                        a: Box::new(MirValue::Use(ra)),
                        b: Box::new(MirValue::Use(rb)),
                    },
                });
                Ok(4)
            }
            0x20 => {
                // THREAD_IDX Rd, dim — GPU: get thread index
                if pc + 2 >= bytecode.len() {
                    return Err(ImportError::UnexpectedEnd { offset: pc, expected: 2 });
                }
                let rd = format!("gp_{}", bytecode[pc + 1] as usize);
                let dim = bytecode[pc + 2] as u32;
                self.current_block.push(MirStatement::ThreadIndex { dim, destination: rd });
                Ok(3)
            }
            0x21 => {
                // SYNC_THREADS — GPU: barrier synchronization
                self.current_block.push(MirStatement::SyncThreads);
                Ok(1)
            }
            0xFF => {
                // HALT
                self.flush_block(MirTerminator::Return);
                Ok(1)
            }
            _ => Err(ImportError::InvalidOpcode { offset: pc, byte: op }),
        }
    }

    fn flush_block(&mut self, terminator: MirTerminator) {
        if !self.current_block.is_empty() || matches!(terminator, MirTerminator::Return) {
            let label = format!("bb{}", self.block_counter);
            self.block_counter += 1;
            self.blocks.push(MirBlock {
                label,
                statements: std::mem::take(&mut self.current_block),
                terminator,
            });
        }
    }

    /// Get the number of GP registers used.
    pub fn gp_register_count(&self) -> usize {
        self.gp_registers.len()
    }

    /// Get the number of FP registers used.
    pub fn fp_register_count(&self) -> usize {
        self.fp_registers.len()
    }

    /// Check if a register is allocated.
    pub fn is_register_allocated(&self, index: u8) -> bool {
        self.gp_registers.contains_key(&index) || self.fp_registers.contains_key(&index)
    }
}

/// Builder for creating Flux programs that compile to GPU kernels.
pub struct FluxGpuBuilder {
    module: MirModule,
}

impl FluxGpuBuilder {
    /// Create a new GPU kernel builder.
    pub fn new(name: &str) -> Self {
        Self {
            module: MirModule {
                name: name.to_string(),
                functions: Vec::new(),
                imports: Vec::new(),
            },
        }
    }

    /// Add a construct import (git-native GPU capability).
    pub fn import_construct(mut self, repo: &str, version: &str, symbol: &str) -> Self {
        self.module.imports.push(ConstructImport {
            repo: repo.to_string(),
            version: version.to_string(),
            symbol: symbol.to_string(),
            identity_did: None,
        });
        self
    }

    /// Build a simple map kernel: apply a function to each element.
    pub fn build_map_kernel(
        name: &str,
        block_dim: u32,
    ) -> MirFunction {
        let thread_idx = "thread_idx".to_string();
        let block_dim_var = "block_dim".to_string();

        MirFunction {
            name: name.to_string(),
            params: vec![
                ("input".to_string(), MirType::GpuPointer {
                    pointee: Box::new(MirType::F32),
                    address_space: GpuAddressSpace::Global,
                }),
                ("output".to_string(), MirType::GpuPointer {
                    pointee: Box::new(MirType::F32),
                    address_space: GpuAddressSpace::Global,
                }),
                ("len".to_string(), MirType::I32),
            ],
            return_type: None,
            blocks: vec![
                MirBlock {
                    label: "bb0".to_string(),
                    statements: vec![
                        MirStatement::ThreadIndex { dim: 0, destination: thread_idx.clone() },
                        MirStatement::Assign {
                            destination: "global_idx".to_string(),
                            value: MirValue::BinaryOp {
                                op: MirBinOp::Add,
                                left: Box::new(MirValue::Use(thread_idx)),
                                right: Box::new(MirValue::ConstInt(0)),
                            },
                        },
                    ],
                    terminator: MirTerminator::Branch {
                        condition: "in_bounds".to_string(),
                        true_block: "bb1".to_string(),
                        false_block: "bb2".to_string(),
                    },
                },
                MirBlock {
                    label: "bb1".to_string(),
                    statements: vec![
                        MirStatement::Load {
                            destination: "val".to_string(),
                            source: "input".to_string(),
                            ty: MirType::F32,
                        },
                        MirStatement::Assign {
                            destination: "result".to_string(),
                            value: MirValue::UnaryOp {
                                op: MirUnOp::Abs,
                                operand: Box::new(MirValue::Use("val".to_string())),
                            },
                        },
                        MirStatement::Store {
                            destination: "output".to_string(),
                            value: "result".to_string(),
                            ty: MirType::F32,
                        },
                    ],
                    terminator: MirTerminator::Goto("bb2".to_string()),
                },
                MirBlock {
                    label: "bb2".to_string(),
                    statements: vec![],
                    terminator: MirTerminator::KernelReturn { value: String::new() },
                },
            ],
            gpu_meta: Some(GpuKernelMeta {
                grid_dim: (1, 1, 1),
                block_dim: (block_dim, 1, 1),
                shared_mem_bytes: 0,
                uses_tensor_cores: false,
            }),
        }
    }

    /// Build the module.
    pub fn build(self) -> MirModule {
        self.module
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_movi_halt() {
        // MOVI R0, 42; HALT
        let bytecode = vec![0x01, 0x00, 0x2A, 0x00, 0xFF];
        let config = ImportConfig::default();
        let module = FluxToMir::translate(&bytecode, &config).unwrap();
        assert_eq!(module.functions.len(), 1);
        assert_eq!(module.functions[0].name, "flux_main");
        // Should have at least one block with the MOVI assignment
        assert!(!module.functions[0].blocks.is_empty());
    }

    #[test]
    fn test_add_instruction() {
        // MOVI R0, 10; MOVI R1, 20; ADD R2, R0, R1; HALT
        let bytecode = vec![
            0x01, 0x00, 0x0A, 0x00,  // MOVI R0, 10
            0x01, 0x01, 0x14, 0x00,  // MOVI R1, 20
            0x02, 0x02, 0x00, 0x01,  // ADD R2, R0, R1
            0xFF,                     // HALT
        ];
        let module = FluxToMir::translate(&bytecode, &ImportConfig::default()).unwrap();
        let func = &module.functions[0];
        // Should have statements: MOVI, MOVI, ADD
        let total_stmts: usize = func.blocks.iter().map(|b| b.statements.len()).sum();
        assert_eq!(total_stmts, 3);
    }

    #[test]
    fn test_ternary_add() {
        // TADD R2, R0, R1 — ternary addition
        let bytecode = vec![
            0x01, 0x00, 0x01, 0x00,  // MOVI R0, 1
            0x01, 0x01, 0xFF, 0xFF,  // MOVI R1, -1 (0xFFFF as i16)
            0x10, 0x02, 0x00, 0x01,  // TADD R2, R0, R1
            0xFF,                     // HALT
        ];
        let module = FluxToMir::translate(&bytecode, &ImportConfig::default()).unwrap();
        let func = &module.functions[0];
        // The TADD should produce a TernaryOp in the MIR
        let total_stmts: usize = func.blocks.iter().map(|b| b.statements.len()).sum();
        assert_eq!(total_stmts, 3);
    }

    #[test]
    fn test_thread_index() {
        // THREAD_IDX R0, 0; HALT
        let bytecode = vec![0x20, 0x00, 0x00, 0xFF];
        let module = FluxToMir::translate(&bytecode, &ImportConfig::default()).unwrap();
        let func = &module.functions[0];
        assert!(func.gpu_meta.is_some());
        let meta = func.gpu_meta.as_ref().unwrap();
        assert_eq!(meta.block_dim.0, 1024);
    }

    #[test]
    fn test_sync_threads() {
        // SYNC_THREADS; HALT
        let bytecode = vec![0x21, 0xFF];
        let module = FluxToMir::translate(&bytecode, &ImportConfig::default()).unwrap();
        let func = &module.functions[0];
        let has_sync = func.blocks.iter().any(|b| {
            b.statements.iter().any(|s| matches!(s, MirStatement::SyncThreads))
        });
        assert!(has_sync);
    }

    #[test]
    fn test_map_kernel_builder() {
        let kernel = FluxGpuBuilder::build_map_kernel("abs_map", 256);
        assert_eq!(kernel.name, "abs_map");
        assert_eq!(kernel.params.len(), 3);
        assert_eq!(kernel.blocks.len(), 3);
        let meta = kernel.gpu_meta.as_ref().unwrap();
        assert_eq!(meta.block_dim.0, 256);
    }

    #[test]
    fn test_invalid_opcode() {
        let bytecode = vec![0xFE]; // Invalid opcode
        let result = FluxToMir::translate(&bytecode, &ImportConfig::default());
        assert!(result.is_err());
        if let Err(ImportError::InvalidOpcode { offset, byte }) = result {
            assert_eq!(offset, 0);
            assert_eq!(byte, 0xFE);
        } else {
            panic!("Expected InvalidOpcode error");
        }
    }

    #[test]
    fn test_unexpected_end() {
        let bytecode = vec![0x01, 0x00]; // MOVI without operands
        let result = FluxToMir::translate(&bytecode, &ImportConfig::default());
        assert!(result.is_err());
        assert!(matches!(result.unwrap_err(), ImportError::UnexpectedEnd { .. }));
    }

    #[test]
    fn test_construct_import() {
        let builder = FluxGpuBuilder::new("test_module")
            .import_construct(
                "SuperInstance/ternary-attention-kernel",
                "v2.0.0",
                "ternary_attention_forward",
            );
        let module = builder.build();
        assert_eq!(module.imports.len(), 1);
        assert_eq!(module.imports[0].symbol, "ternary_attention_forward");
    }

    #[test]
    fn test_gpu_address_spaces() {
        let global = GpuAddressSpace::Global;
        let shared = GpuAddressSpace::Shared;
        assert_ne!(global, shared);

        let ptr_type = MirType::GpuPointer {
            pointee: Box::new(MirType::F32),
            address_space: GpuAddressSpace::Shared,
        };
        assert_eq!(ptr_type, MirType::GpuPointer {
            pointee: Box::new(MirType::F32),
            address_space: GpuAddressSpace::Shared,
        });
    }

    #[test]
    fn test_mir_types() {
        assert_eq!(MirType::Ternary, MirType::Ternary);
        assert_ne!(MirType::I32, MirType::F32);
        assert_ne!(MirType::Ternary, MirType::I8);
    }
}
